config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/interest' => 'home#interest'
  get 'home/search' => 'home#search'
  post 'home/search' => 'home#search'
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show, :update, :destroy] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @home_page = true
        @events = Event.all
    end

    def interest
        @interests = {
            'Outdoors' => ['Cycling', 'Camping', 'Hiking', 'Fishing'],
            'Technology' => ['Crypto', 'SEO', 'E-Commerce'],
            'Health' => ['Fitness', 'Nutrition', 'Yoga'],
            'Education' => ['Math', 'Engineering', 'Science'],
            'Food & Drink' => ['Coffee', 'Vegan', 'Wine'],
        }
        @category = @interests.keys.each { |cat| cat }   
        @sub_category = @interests.values.each { |sub| sub } 
    end

    def search
        @events = Event.where(nil)
        @searched_results = @events.filter(filtering_params(params)).order(:updated_at)
        # @searched_results = @events.where("title ILIKE :search OR category ILIKE :search", {search: "%#{params[:search_fields]}%"})
        @category = @events.order(:category).distinct.pluck(:category)
        @date = @events.where(date: Date.today)

        respond_to do |format|
          format.html
          format.json { render json: @searched_results }
          format.js # remote: true is sent a js format and sends you to search.js.erb
        end
      end
    
      private

      def filtering_params(params)
        params.slice(:search_fields)
      end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_accordion.html.erb
<div id="accordion">
  <div class="card border-0">
    <div class="card-header bg-white" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link d-flex" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Date <i class="material-icons ml-auto"> keyboard_arrow_down </i>
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
            <%= bootstrap_form_with url: home_search_path, method: :get, local: true do |f| %>
                <div class="input-group mb-3" id="datepicker" data-provide="datepicker">
                    <%= f.text_field :search_fields, id: "datepicker", data:{ provide:'datepicker' }, class: 'input-sm form-control text-small', onchange: 'this.form.submit();' %> 
                </div>
                <%= f.submit "Search", class: "d-none", :name => nil %>
            <% end %>
      </div>
    </div>
  </div>
  <div class="card border-0">
    <div class="card-header bg-white" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link d-flex" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Price range <i class="material-icons ml-auto"> keyboard_arrow_down </i>
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        2
      </div>
    </div>
  </div>
  <div class="card border-0">
    <div class="card-header bg-white" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link d-flex" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Category <i class="material-icons ml-auto"> keyboard_arrow_down </i>
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        <%= bootstrap_form_with url: home_search_path, method: :get, local: true do |f| %>
            <div class="form-group">
                <%= f.select :search_fields, @category, {}, { class: 'form-control', onchange: 'this.form.submit();' } %> 
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if signed_in? %>
    <div class="container my-2">
        <div class="card-deck my-3">
            <% @events.each_with_index {|x, i| %>
                <div class="col-md-3 col-sm-6 col-xs-12 px-0 mb-4">
                    <%= link_to event_path(x.id), :class => "card card-hyperlink border-0 ml-0" do %>
                        <%= image_tag("exp/#{rand(1..30)}.png", class: "card-img-top ml-3") %>
                        <div class="card-body">
                            <p class="card-title small my-0"> <%= "#{x.category} | #{x.sub_category}" %> </p>
                            <h5 class="card-title my-1"> <%= x.title %> </h5>
                            <p class="card-text small my-0">From $<%= x.cost %> per person</p>
                            <p class="card-text small my-1"><%= x.date.strftime('%A, %B %dth %Y') %></p>
                            <p class="card-text small my-1"><%= x.time %></p>
                            <% x.participants.first(5).each do |y| %>
                                <% @participant = User.find(y) %>
                                <%= link_to(image_tag(@participant.avatar.small_thumb.url, class: "avatar-xs mt-2"), user_path(y)) %>
                            <% end %></br>
                            <small class="text-muted"><%="#{x.participants.count} people attending" %></small>
                        </div>
                    <% end %>
                </div>
            <% } %>
        </div>
    </div>

<% else %>

    <div class="container-fluid">
        <div class="d-flex justify-content-center headline">
            <h1>WHAT THE FUCK SHOULD I DO?</h1>
        </div>
    </div>
    <div class="container-fluid d-flex h-25 justify-content-center">
        <div class="row align-self-center">
            <ul>
                <li class="btn">
                    <a href="#exampleModal1" class="align-middle mr-2 btn btn-warning" data-toggle="modal">Sign up</a>
                    <div id="exampleModal1" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-sm" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div id="clearance" class="sign-up">
                            
                                <%= render partial: '/users/form' %>
                    
                            </div>           
                        </div>
                        <div class="modal-footer">
                        </div>
                        </div>
                    </div>
                    </div>
                </li>
                <li class="btn">
                    <a href="#exampleModal2" class="align-middle mr-5 btn btn-warning" data-toggle="modal">Log in</a>
                    <div id="exampleModal2" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-sm" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <%#= link_to "Sign in with Google", "/auth/google_oauth2" %>
                            <div style="width: 100%; height: 16px; border-bottom: 1px solid #bbb; text-align: center">
                                <span style="background-color: #FFF; padding: 0 10px;">
                                or
                                </span>
                            </div></br>
                            <div id="clearance" class="sign-in">
                                <!-- <span style="color:#aaa; font-size: 0.8em;"><%= t(".Login") %></span> -->
                                <%= render partial: '/sessions/form' %>
                            </div>
                        </div>
                        <div class="modal-footer">
                        </div>
                        </div>
                    </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
<% end %>

app/views/home/interest.html.erb
<div class="container">
    <h3>Select all the events you're interested in</h3></br>
    <div class="card-deck mx-0">
        <% @sub_category.each_with_index {|x, i| %>
            <% x.each { |y| %>
                <div class="col-md-2 col-sm-4 col-xs-16 px-0 mb-4">
                    <%= link_to "/", :class => "card btn py-0 px-0 text-white bg-success" do %>
                        <div class="card-body">
                            <h5 class="card-title"> <%= y %> </h5>
                        </div>
                    <% end %>
                </div>
            <% } %>    
        <% } %>
    </div>
</div>
    <%#= bootstrap_form_with(model: @user, local: true ) do |f| %>
      <%#= f.button :interests %>
      <%#= f.submit "Create" %>
    <%# end %>

app/views/home/search.html.erb
<% if signed_in? %>

<div class="container my-4">
    <div class="row py-3">
        <div class="col-4 col-sm-3 pl-0 pr-5">
            <%= render partial: '/home/accordion' %>
        </div>

        <div class="col-8 col-sm-9">
            <div class="card-deck my-3">
                <% @searched_results.each_with_index {|x, i| %>
                    <div class="col-md-3 col-sm-6 col-xs-12 px-0 mb-4">
                        <%= link_to event_path(x.id), :class => "card card-hyperlink border-0 ml-0" do %>
                            <%= image_tag("exp/#{rand(1..30)}.png", class: "card-img-top ml-3") %>
                            <div class="card-body">
                                <p class="card-title small my-0"> <%= "#{x.category} | #{x.sub_category}" %> </p>
                                <h5 class="card-title my-1"> <%= x.title %> </h5>
                                <p class="card-text small my-0">From $<%= x.cost %> per person</p>
                                <p class="card-text small my-1"><%= x.date.strftime('%A, %B %dth %Y') %></p>
                                <p class="card-text small my-1"><%= x.time %></p>
                                <% x.participants.first(5).each do |y| %>
                                    <% @participant = User.find(y) %>
                                    <%= link_to(image_tag(@participant.avatar.small_thumb.url, class: "avatar-xs mt-2"), user_path(y)) %>
                                <% end %></br>
                                <small class="text-muted"><%="#{x.participants.count} people attending" %></small>
                            </div>
                        <% end %>
                    </div>
                <% } %>
            </div>
        </div>
    </div>
</div>

<% end %>

<!--
<script>
  $("#search_fields").on("keyup", function(){
    autocomplete();
  });

  function autocomplete(){
    $.ajax({
      url: '/home/search',
      type: 'POST',
      data: $("#event-search").serialize() + "&authenticity_token=" + encodeURIComponent(AUTH_TOKEN), //takes the form data and authenticity toke and converts it into a standard URL
      dataType: 'json', //specify what type of data you're expecting back from the servers
      error: function() {
          console.log("Something went wrong");
      },
      success: function(data) { 
        
        let container = document.querySelector('.card-deck')
        container.innerHTML = ""
        data.forEach(function(element) {
           let card = `<div class="col-md-3 col-sm-6 col-xs-12 px-0 mb-4">
                            <a class="card card-hyperlink" href="/events/${element.id}">
                                <img class="card-img-top" src="https://a0.muscache.com/im/pictures/65441227/bb1eb2dd_original.jpg?aki_policy=large" alt="Card image cap">
                                <div class="card-body">
                                    <p class="card-title">${element.category}</p>
                                    <h5 class="card-title"> ${element.title}</h5>
                                    <p class="card-text">From $${element.price} per night | Free cancellation</p>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">ratings | Superhost</small>
                                </div>
                            </a>            
                      </div>`
          container.innerHTML += card
        });
      }
    });
  }
</script>
-->