config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/interest' => 'home#interest'
  get 'home/search' => 'home#search'
  post 'home/search' => 'home#search'
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show, :update, :destroy] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg ">

  <%= link_to '/' do %>
  <%= image_tag("logo.png", class: "navbar-brand ml-4", width: "55px", height: "55px", alt: "Logo") %>
  <% end %>		

  <% if signed_in? %>
    <div id="search-div" class="mt-4 ml-3">
      <%= bootstrap_form_with url: home_search_path, method: :get, id: "event-search", local: true do |f| %>
        <%= f.text_field :search_fields, hide_label: true, placeholder: "Try \"Scuba Diving\"", list: "list" %>
        <%= f.submit "Search", class: "d-none", :name => nil %>
        <datalist id="list"></datalist>
      <% end %>
    </div>  
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
    <% if signed_in? %>
      <ul class="navbar-nav ml-auto">
          <li class="nav-item mt-4">
            <%= link_to "Create an event", new_event_path, class: "align-middle mr-5 text-dark" %>
          </li> 
        <% if !current_user.participant? %>
          <li class="nav-item mt-4">
            <%= link_to "My Events", users_path, class: "align-middle mr-5 text-dark" %>
          </li> 
        <% end %>
        <li class="nav-item dropdown mr-4">
          <%= link_to(image_tag(current_user.avatar.small_thumb.url, class: "avatar-nav"), "/#", class: "nav-link align-middle mt-1", id: "navbarDropdown", role: "button", :'data-toggle' => 'dropdown', 'aria-haspopup' => true, 'aria-expanded' => false ) %>   
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Profile", edit_user_path(current_user), class: "text-dark" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Sign Out", sign_out_path, method: :delete, class: "text-dark" %>          
          </div>
        </li>
      </ul>    
    <% else %>
    <% end %>

  </div>
</nav>
<script>
  $("#event-search").on("keyup", function(){
    autocomplete();
  });

  $("#search_fields").on("change", function(e){
    document.querySelectorAll("option").forEach(function(elem){
      if (elem.value == e.target.value) {
        $("#event-search").submit()
      }
    })
  });

  function autocomplete(){
    $.ajax({
      url: '/home/search',
      type: 'POST',
      data: $("#event-search").serialize() + "&authenticity_token=" + encodeURIComponent(AUTH_TOKEN), //takes the form data and authenticity toke and converts it into a standard URL
      dataType: 'json', //specify what type of data you're expecting back from the servers
      error: function() {
          console.log("Something went wrong");
      },
      success: function(data) { // If success
        $("#list").html("");  // Return data (UL list?) and insert it in the <div id="list"></div>
        let resultArray = []
        data.forEach(function(element) {
          resultArray.push(element.title);
          resultArray.push(element.sub_category);
        });
        resultArray = Array.from(new Set(resultArray))

        resultArray.forEach(function(elem){
          var option = document.createElement("option");
          option.value = elem;

          //append option to list
          $("#list").append(option);

        })
      }
    });
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>WhatTheFuckShouldIDo</title>

  <%= csrf_meta_tag %>

  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= @home_page && !signed_in? ? 'homepage' : ''%>">
  <%= render 'layouts/navigation' %>

  <div id="flash-alert">
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %> fade show">
            <%= value %>
      </div>
    <% end %>
  </div>

  <%= yield %>

  <script>
    $("#flash-alert").fadeTo(2000, 500).fadeOut(500, function(){
      $("#flash-alert").alert('close');
    });
  </script>
</body>
</html>